name: dotfiles

path: /Users/moonlight/Workspace/moonlight8978

windows:
  - name: &ws1 ./dotfiles
    panes:
      - name: code
        flex: 100
        commands:
          - command: $EDITOR
        path: *ws1
        focus: true
      - name: terminal
        flex: 45
        path: *ws1

