- name: Setup Mac machine
  hosts: all
  vars_files:
    - values.yaml
  roles:
    - role: geerlingguy.mac.homebrew
      tags:
        - homebrew
  tasks:
    - name: Install pip packages
      tags: 
        - python
      loop: "{{ pip_packages }}"
      ansible.builtin.pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        executable: pip

    - name: Download huggingface models
      tags:
        - hf
      loop: "{{ hf_models }}"
      ansible.builtin.shell: "huggingface-cli download {{ item }} --local-dir .models --local-dir-use-symlinks False"


    - import_tasks: ansible/tasks/git_clone.yaml
      tags: 
        - asdf
      vars:
        repo: https://github.com/asdf-vm/asdf.git
        version: "{{ asdf_version }}"
        dest: "{{ lookup('env', 'HOME') }}/.asdf"

    - name: Install asdf plugins
      tags:
        - asdf
      loop: "{{ asdf_plugins }}"
      ansible.builtin.shell: "asdf plugin list | grep {{ item.name | default(item) }} || (asdf plugin add {{ item.name | default(item) }} && exit 100)" 
      register: asdf_install_plugin
      changed_when: asdf_install_plugin.rc == 100
      failed_when: asdf_install_plugin.rc > 0

    - name: Install asdf default tools
      tags:
        - asdf
      ansible.builtin.command: asdf install

    - import_tasks: ansible/tasks/git_clone.yaml
      tags:
        - tmux
      vars:
        repo: https://github.com/tmux-plugins/tpm.git
        version: master
        dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
