- name: Setup Mac machine
  hosts: localhost
  vars_files:
    - values.yaml
  roles:
    - role: ansible/roles/tmux
      tags:
        - tmux

- name: Setup mac mini
  hosts: localhost
  tags:
    - mini
  vars_files:
    - values.yaml
  become: true
  roles:
    - role: ansible/roles/disks
      vars:
        mounts: "{{disks.mini.mounts}}"
        disk: "{{disks.mini.disk}}"

- name: Setup az macbook
  hosts: localhost
  tags:
    - azmb
  vars_files:
    - values.yaml
  become: true
  roles:
    - role: ansible/roles/disks
      vars:
        mounts: "{{disks.azmb.mounts}}"
        disk: "{{disks.azmb.disk}}"

- name: Setup casio M1
  hosts: localhost
  tags:
    - casiom1
  vars_files:
    - values.yaml
  become: true
  roles:
    - role: ansible/roles/disks
      vars:
        mounts: "{{disks.casiom1.mounts}}"
        disk: "{{disks.casiom1.disk}}"

  # tasks:
  #   - name: Download huggingface models
  #     tags:
  #       - hf
  #     loop: "{{ hf_models }}"
  #     ansible.builtin.shell: "huggingface-cli download {{ item }} --local-dir .models --local-dir-use-symlinks False"

  #   - import_tasks: ansible/tasks/debian.yml
  #     tags:
  #       - debian
  #     vars:
  #       packages: "{{ apt_packages }}"
