- name: Setup Mac machine
  hosts: localhost
  vars_files:
    - values.yaml
  roles:
    - role: ansible/roles/asdf
      tags:
        - asdf
    - role: ansible/roles/tmux
      tags:
        - tmux
  # tasks:
  #   - name: Download huggingface models
  #     tags:
  #       - hf
  #     loop: "{{ hf_models }}"
  #     ansible.builtin.shell: "huggingface-cli download {{ item }} --local-dir .models --local-dir-use-symlinks False"

  #   - import_tasks: ansible/tasks/debian.yml
  #     tags:
  #       - debian
  #     vars:
  #       packages: "{{ apt_packages }}"
