version: 3
tasks:
  nix:repair:
    cmd: sudo nix-store --verify --check-contents --repair

  nix:update:
    dir: nix
    cmd: nix flake update

  nix:copy:
    dir: nix
    cmd: sudo cp -R * /etc/nix-darwin

  nix:rebuild:
    dir: nix
    cmds:
      - sudo ulimit -n 65536
      - sudo darwin-rebuild switch --impure

  asdf:
    cmd: ansible-playbook main.yml --tag asdf {{.CLI_ARGS}}

  home:*:
    vars:
      TARGET: "{{index .MATCH 0}}"
    cmds:
      - stow -t ~ {{.TARGET}}

  config:*:
    vars:
      TARGET: "{{index .MATCH 0}}"
    cmds:
      - mkdir -p ~/.config/{{.TARGET}}
      - stow -t ~/.config/{{.TARGET}} {{.TARGET}}

  mise:
    cmds:
      - mise install

  disk:uuid:
    vars:
      DISK: "{{index .CLI_ARGS_LIST 0}}"
    cmd: |
      UUID=$(diskutil info /dev/{{.DISK}} | grep UUID | head -n 1 | awk -F ':' '{print $2}' | tr -s ' ')
      echo $UUID
      echo $UUID | pbcopy
