"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$fill\
$kubernetes\
$line_break\
$time\
$character"""

[aws]
symbol = ' '
disabled = false
format = 'on [$symbol($profile )(\($region\))]($style)'

[kubernetes]
symbol = '󱃾 '
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'

[time]
disabled = false
format = '[$time]($style) '
