- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Check zsh existence
  ansible.builtin.command: "which zsh"
  register: zsh_check
  changed_when: false
  failed_when: false

- name: Change default shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_check.stdout }}"
  when: zsh_check.rc == 0
