name: telegram-message-parse
description: Parse columns to message for telegram-action
author: _MoonLight_ <moonlight8978@gmail.com>

inputs:
  message:
    description: Message
    required: false
    default: ''
  columns:
    description: |
      Columns definition following this format
      |W| <icon> |W| <title> |W| <content>
      |W| <icon> |W| <title> |W| <content>
      |W| <icon> |W| <title> |W| <content>
    required: false
    default: ''

outputs:
  message:
    description: Message

runs:
  using: node20
  main: dist/index.js
