name: Test discord message

on:
  push:
    branches:
      - action/git-head-commit
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: git-head-commit
        if: ${{ always() }}
        uses: moonlight8978/dotfiles/.github/actions/git-head-commit@main
      - uses: moonlight8978/dotfiles/.github/actions/console-log@main
        if: ${{ always() }}
        with:
          message: |
            author: ${{ steps.git-head-commit.outputs.author }}
            sha-short: ${{ steps.git-head-commit.outputs.sha-short }}
            sha: ${{ steps.git-head-commit.outputs.sha }}
            branch: ${{ steps.git-head-commit.outputs.branch }}
            message: ${{ steps.git-head-commit.outputs.message }}
