name: Test

on:
  push:
    branches:
      - feat/google-drive-upload
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: upload-artifacts
        uses: moonlight8978/dotfiles/.github/actions/google-drive-upload@main
        with:
          service-account-base64: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_BASE64 }}
          folder: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
          file: .github/actions/google-drive-upload/Test.csv
          destination: a/b/c/d/e/f/${{ github.run_id }}/Test.csv

      - uses: moonlight8978/dotfiles/.github/actions/console-log@main
        if: ${{ always() }}
        with:
          message: |
            file-size: ${{ steps.upload-artifacts.outputs.file-size }} bytes
            file-url: ${{ steps.upload-artifacts.outputs.file-url }}
